'clap' upgrade(v3 to v4) and refactoring
lablup/raftify pull request #109
Opened 2024-08-10 10:13 UTC by CHOUMnote

Previously, we were using `version 3 of Clap`, so we upgraded to `version 4`. However, this caused compile errors due to the version upgrade, leading us to remove a lot of legacy code and refactor the project.

Note) I tested the `debug` option as thoroughly as possible, but I was unable to test the `dump` option because I didn't know how to use it.

2024-08-12 05:31 UTC, jopemachine commented on raftify/src/cli/mod.rs
> +    Nan,
`Nan` seems to have been in the example code
Please delete it.

2024-08-12 05:59 UTC, jopemachine commented on raftify/src/cli/mod.rs
> +    _custom_args: Option<Vec<String>>,
The function is also used when exposing the CLI module to the Python side. When calling `cli_handler` from the Rust side, `custom_args` is None, but when calling from the Python side, you need to pass a value to `custom_args` and parse it accordingly.

So, I suggest making the following changes

```rs
pub async fn cli_handler<
    LogEntry: AbstractLogEntry + Debug + Send + 'static,
    FSM: AbstractStateMachine + Debug + Clone + Send + Sync + 'static,
>(
    args: Option<Vec<String>>,
) -> Result<()> {
    let app = match args {
        Some(args) => App::parse_from(args),
        None => App::parse(),
    };
...
```

2024-08-12 06:00 UTC, jopemachine commented on raftify/src/cli/mod.rs
> +            panic!("Command is not exist~");
This part is unnecessary if you remove NaN from Command.

2024-08-12 06:05 UTC, jopemachine commented on raftify/src/cli/mod.rs
> +    ///List all log entries
Missing whitespace.

```
/// List all log entries
```

2024-08-12 06:07 UTC, jopemachine commented on raftify/src/cli/mod.rs
> +/// it's expected [`App::command`] is debug, [`DebugSubcommands::PersistedAll::path`] is./logs
This comment seems unnecessary.
Please delete

2024-08-13 00:38 UTC, jopemachine requested changes
Thanks for your PR!
Please check the review

2024-08-13 07:37 UTC, CHOUMnote commented
@jopemachine I have applied the code. Please review it.

2024-08-13 07:51 UTC, jopemachine commented on raftify/src/cli/mod.rs
> +/// CLI parser
Please do not leave unnecessary comments.

2024-08-13 07:51 UTC, jopemachine commented on raftify/src/cli/mod.rs
> +// Subcommand Select
Same here

2024-08-13 07:51 UTC, jopemachine commented on raftify/src/cli/mod.rs
> +    /// required main commands
Same here

2024-08-13 07:51 UTC, jopemachine commented on raftify/src/cli/mod.rs
> +        // using python side
Same here

2024-08-13 07:51 UTC, jopemachine commented on raftify/src/cli/mod.rs
> +        // using env::args
There are several unnecessary whitespaces here.
Running `cargo fmt` before committing can prevent such mistakes.

2024-08-13 08:16 UTC, CHOUMnote commented
i have a question. do you recommend not to write comments as much as possible?

2024-08-13 08:19 UTC, jopemachine commented
> i have a question. do you recommend not to write comments as much as possible?

No, I'm not saying don't comment; rather, the code should be self-explanatory.

Comments should explain things that cannot be explained by the code itself, not repeat what the code already expresses.

I think this code is already sufficiently self-explanatory, so additional comments are not necessary.

2024-08-13 08:27 UTC, merged

2024-08-13 08:28 UTC, jopemachine commented
@CHOUMnote Thanks for your contribution! ❤️